import archiver from 'archiver';
import { PassThrough } from 'stream';
import type { BookManifest } from './types';

export interface AssembleEpubInput {
  manifest: BookManifest;
  coverBytes: Uint8Array | null;
  pageBytes: (Uint8Array | null)[];
  author?: string;
}

interface ImageEntry {
  id: string;
  fname: string;
  mime: string;
}

interface Chapter {
  id: string;
  title: string;
  html: string;
}

export async function assembleEpub(input: AssembleEpubInput): Promise<Buffer> {
  const { manifest, coverBytes, pageBytes, author = 'Aditya Sankhla' } = input;

  const pass = new PassThrough();
  const chunks: Buffer[] = [];
  pass.on('data', (c) => chunks.push(c));

  const archive = archiver('zip', { store: true });
  archive.pipe(pass);

  archive.append('application/epub+zip', { name: 'mimetype' });

  archive.append(
    `<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>`,
    { name: 'META-INF/container.xml' },
  );

  const imageEntries: ImageEntry[] = [];

  const addImage = (bytes: Uint8Array | null, id: string): string | null => {
    if (!bytes || bytes.length < 2) return null;
    const mime = bytes[0] === 0xff && bytes[1] === 0xd8 ? 'image/jpeg' : 'image/png';
    const ext = mime === 'image/jpeg' ? 'jpg' : 'png';
    const fname = `${id}.${ext}`;
    archive.append(Buffer.from(bytes), { name: `OEBPS/images/${fname}` });
    imageEntries.push({ id, fname, mime });
    return `images/${fname}`;
  };

  const coverSrc = addImage(coverBytes, 'cover');
  const pageSrcs: (string | null)[] = [];
  for (let i = 0; i < manifest.pages.length; i++) {
    const page = manifest.pages[i];
    pageSrcs.push(addImage(pageBytes[i], `page${page.pageNumber}`));
  }

  const chapters: Chapter[] = [];

  chapters.push({
    id: 'cover',
    title: manifest.title,
    html: `<html><body style="text-align:center">
${coverSrc ? `<img src="${coverSrc}" style="max-width:100%;max-height:90vh" />` : ''}
<h1>${manifest.title}</h1>
<p><em>${manifest.subtitle || ''}</em></p>
<p>By ${author}</p></body></html>`,
  });

  chapters.push({
    id: 'dedication',
    title: 'Dedication',
    html:
      '<html><body style="text-align:center;padding-top:30%"><p><em>For every little reader<br/>who dreams at bedtime.</em></p></body></html>',
  });

  for (let i = 0; i < manifest.pages.length; i++) {
    const page = manifest.pages[i];
    const src = pageSrcs[i];
    chapters.push({
      id: `page${page.pageNumber}`,
      title: `Page ${page.pageNumber}`,
      html: `<html><body style="text-align:center">
${src ? `<img src="${src}" style="max-width:100%;max-height:70vh;margin-bottom:20px" />` : ''}
<p style="font-size:1.3em;line-height:1.6;padding:10px 20px">${page.text}</p></body></html>`,
    });
  }

  chapters.push({
    id: 'theend',
    title: 'The End',
    html:
      '<html><body style="text-align:center;padding-top:30%"><h1 style="color:#5959aa">The End</h1></body></html>',
  });

  chapters.push({
    id: 'note',
    title: 'A Note for Parents',
    html: `<html><body style="padding:20px"><h2>A Note for Parents</h2><p>This book was created using artificial intelligence. Both the story and the illustrations were generated by AI, guided by a new dad who wanted to create something special for his son. We hope this little book makes your child smile at bedtime.</p></body></html>`,
  });

  for (const ch of chapters) {
    archive.append(ch.html, { name: `OEBPS/${ch.id}.xhtml` });
  }

  const navItems = chapters
    .map((ch) => `      <li><a href="${ch.id}.xhtml">${ch.title}</a></li>`)
    .join('\n');

  archive.append(
    `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head><title>Table of Contents</title></head>
<body>
  <nav epub:type="toc" id="toc">
    <h1>Table of Contents</h1>
    <ol>
${navItems}
    </ol>
  </nav>
</body>
</html>`,
    { name: 'OEBPS/nav.xhtml' },
  );

  const manifestItems = chapters
    .map((ch) => `    <item id="${ch.id}" href="${ch.id}.xhtml" media-type="application/xhtml+xml"/>`)
    .join('\n');
  const imageItems = imageEntries
    .map(
      (img) =>
        `    <item id="img_${img.id}" href="images/${img.fname}" media-type="${img.mime}"/>`,
    )
    .join('\n');
  const spineItems = chapters.map((ch) => `    <itemref idref="${ch.id}"/>`).join('\n');
  const slug = manifest.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+/g, '-');
  const bookId = slug + '-' + new Date().getFullYear();

  archive.append(
    `<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="bookid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>${manifest.title}</dc:title>
    <dc:creator>${author}</dc:creator>
    <dc:language>en</dc:language>
    <dc:identifier id="bookid">${bookId}</dc:identifier>
    <meta property="dcterms:modified">${new Date().toISOString().split('.')[0]}Z</meta>
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
${manifestItems}
${imageItems}
  </manifest>
  <spine toc="ncx">
${spineItems}
  </spine>
</package>`,
    { name: 'OEBPS/content.opf' },
  );

  const navPoints = chapters
    .map(
      (ch, i) =>
        `    <navPoint id="nav${i}" playOrder="${i + 1}"><navLabel><text>${ch.title}</text></navLabel><content src="${ch.id}.xhtml"/></navPoint>`,
    )
    .join('\n');

  archive.append(
    `<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head><meta name="dtb:uid" content="${bookId}"/></head>
  <docTitle><text>${manifest.title}</text></docTitle>
  <navMap>
${navPoints}
  </navMap>
</ncx>`,
    { name: 'OEBPS/toc.ncx' },
  );

  await archive.finalize();
  await new Promise<void>((resolve) => pass.on('end', () => resolve()));

  return Buffer.concat(chunks);
}
